### ISSUE TITLE
Crystal 0.20.4

### ISSUE THREAD

**Issue by crisward** [kemalcr/kemal-session-file#4]
Getting this error

```
abstract `def Session::Engine#bigint(session_id : String, k : String, v : Int64)` must be implemented by Session::FileSystemEngine`
```
Using ....

```
Installing kemal-session-file (master)
Installing kemal-session (master)
```

**Comment by sdogruyol** [comment]
@crisward this engine doesn't implement `biginit` yet. Can you use `kemal-session` 0.6.0?

**Comment by crisward** [comment]
Just tried that, different error. I'll drop down to crystal 0.20.3 for now. Thanks...

```yml
  kemal-session:
    github: kemalcr/kemal-session
    version: ~> 0.6.0
  kemal-session-file:
    github: kemalcr/kemal-session-file
    version: ~> 0.3.0
```

```
no overload matches 'Session::FileSystemEngine::StorableObjectConverter.to_json' with types Hash(String, Session::StorableObject), JSON::Builder
Overloads are:
 - Session::FileSystemEngine::StorableObjectConverter.to_json(value : Hash(String, StorableObject), io : IO)
 - Object#to_json(io : IO)
 - Object#to_json()
```
